name: Locker
on:
  schedule:
    - cron: 0 5 * * * # 10:00pm PT
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: stable
      - name: Install Actions
        run: npm ci --prefix ./actions
      - name: Run Locker
        uses: ./actions/locker
        with:
          token: ${{secrets.AZCODE_BOT_PAT}}
          daysSinceClose: 45
          daysSinceUpdate: 7
